### ISSUE TITLE
Multi-objective optimization support

### ISSUE THREAD

**Issue by hongyuanjia** [luca-scr/GA#37]
I love how GA package structure the workflow, which is nice and neat. I am trying to adopt GA package in my resent research work. My work mainly focuses on optimizing architecture design options, which involve multi-object optimization (MOO). Currently, does GA support MOO? If not, are there any plans for support it? Thanks!

**Comment by luca-scr** [comment]
GA package does not support MOO and there is no plan to implement it due to lack of time and interest. When I had to solve a MOO problem I took the strategy to define a fitness function that reduce multiple objective functions into a single (weighted) objective function. It may be simplistic but works reasonable well.

**Comment by hongyuanjia** [comment]
@luca-scr Thanks for the hint. Yeah, whenever it is possible, downgrade the MOO to a mono one is a feasible way. Anyway, thanks for this package!
